### ISSUE TITLE
I have an issue with iKy.

### ISSUE THREAD

**Issue by Bernie254** [kennbroorg/iKy#35]
Hey, I have an issue with iKy... am runnning kali linux 2020.4 and i have followed all the installation steps but the app can't start and am using the latest python 3.9...
here is what being displayed on the screen.

![firefox1 22:45:23](https://user-images.githubusercontent.com/47120407/102801801-c4d7e180-43c6-11eb-98f9-17fd3b3aab73.png)
![Uploading Screenshot 2020-12-21 22:34:39.png…]()

**Comment by KennBro** [comment]
Please, show me the terminal log

**Comment by Bernie254** [comment]
![Screenshot 2020-12-21 22:34:39](https://user-images.githubusercontent.com/47120407/103525251-f73a1200-4e8f-11eb-85f7-976425f205c7.png) Here the terminal. 
 1. first window  that's for redis-server i used sudo redis-server
 2. second window I wake up celery using this command ./celery.sh
 3. third  window I turned on backend app from directory backend  using sudo python3 app.py.
 4. fourth window I  run frontend server using sudo npm start

**Comment by KennBro** [comment]
It is working. The port 5000 is API.
Try http://127.0.0.1:5000/tasklist in your browser.

**Comment by Bernie254** [comment]
when i try http://127.0.0.1:5000/tasklist this is what i got.
![fyg](https://user-images.githubusercontent.com/47120407/104280605-3d5d2a00-54bd-11eb-9eaa-221ab96dd32b.png)

**Comment by Bernie254** [comment]
here is the full list of what's being displayed.
{
  "modules": [
    "peopledatalabs", 
    "twitter_infos", 
    "twitter_comps", 
    "ghostproject", 
    "twitter_info", 
    "twitter_comp", 
    "fullcontact", 
    "usersearch", 
    "socialscan", 
    "tweetiment", 
    "leaklookup", 
    "instagram", 
    "tasklist", 
    "linkedin", 
    "darkpass", 
    "emailrep", 
    "sherlock", 
    "testing", 
    "keybase", 
    "twitter", 
    "apikey", 
    "github", 
    "gitlab", 
    "tiktok", 
    "holehe", 
    "tinder", 
    "search", 
    "reddit", 
    "twint", 
    "leaks", 
    "venmo", 
    "skype", 
    "result/<task_id>", 
    "state/<task_id>/<task_app>"
  ]
}

**Comment by Bernie254** [comment]
what does that means, are they module need to be install or what? please help

**Comment by KennBro** [comment]
That means everything is fine. The backend is working properly. 
Just turn on the frontend and test it.

**Comment by Bernie254** [comment]
thanks for being in touch but the problem persists the frontend is running but it displaying a blank terminal, the command i use is sudo npm start.... even on the browser side nothing but displaying NOT FOUND

![Screenshot 2021-02-08 21:12:39](https://user-images.githubusercontent.com/47120407/107240092-95466c80-6a3a-11eb-8028-18a238def5b9.png)

**Comment by KennBro** [comment]
Ah ok. Your mistake is that port 5000 does not run the frontend, It's the iKy API. 
At the beginning of the issue I understood that your problem was that the backend was not responding because it was referencing port 5000.
The frontend runs on port 4200. 
![expl](https://user-images.githubusercontent.com/32843687/107260863-5b1aa200-6a1d-11eb-8cbf-0ab5f273b5e4.png)

The "NOT FOUND" message is simply that the API does not implement a path to the / (root)

As for npm, two things: 
- It doesn't start with sudo as shown in the image
- Why don't you test the pack without NodeJS? (Only python)
![Screenshot from 2021-02-08 14-48-10](https://user-images.githubusercontent.com/32843687/107261214-d0867280-6a1d-11eb-955b-c380d034b7bf.png)

**Comment by KennBro** [comment]
Reopen if necessary
